### ISSUE TITLE
error running tardis in dev env outside of virtualenv in which package installed

### ISSUE THREAD

**Issue by afmcc** [AgResearch/tardis#15]
crash$ pwd
/dataset/bioinformatics_dev/active/tardis/tardis
crash$ PYTHONPATH=. ./tardis/run.py echo hello
tool args = ['echo', 'hello']
tardis.py : logging this session to /bifo/active/bioinformatics_dev/tardis/tardis/tardis_32xmrJ
Traceback (most recent call last):
  File "./tardis/run.py", line 234, in <module>
    sys.exit(tardis_main())
  File "./tardis/run.py", line 225, in tardis_main
    (exit_code, factory) = run(toolargs,options, checkCommandIsValid = False)
  File "./tardis/run.py", line 74, in run
    job = c.gethpcJob(cmd)
  File "/bifo/active/bioinformatics_dev/tardis/tardis/tardis/conditioner/factory.py", line 553, in gethpcJob
    hpcjob = self.hpcClass(self,conditioned_toolargv)
  File "/bifo/active/bioinformatics_dev/tardis/tardis/tardis/job/slurm.py", line 20, in __init__
    (junk, self.shell_script_template, self.runtime_config_template) = self.get_templates(None, "slurm_shell", "basic_slurm_runtime_environment")
  File "/bifo/active/bioinformatics_dev/tardis/tardis/tardis/job/hpc.py", line 97, in get_templates
    raise tutils.tardisException("error neither  job_template_name nor job_template_filename are defined (and no default available")
tardis.tutils.tutils.tardisException: error neither  job_template_name nor job_template_filename are defined (and no default available
crash$

**Comment by afmcc** [comment]
check log file in working folder for more info
