### ISSUE TITLE
error using --hpctype local 

### ISSUE THREAD

**Issue by afmcc** [AgResearch/tardis#21]
iramohio-01$ tardis -q --hpctype local echo hello
Traceback (most recent call last):
  File "/stash/miniconda3/envs/universal2/bin/tardis", line 6, in <module>
    sys.exit(tardis.run.tardis_main())
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/run.py", line 244, in tardis_main
    (exit_code, factory) = run(command_args, options, checkCommandIsValid = False)
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/run.py", line 70, in run
    job = c.gethpcJob(cmd)
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/conditioner/factory.py", line 550, in gethpcJob
    hpcjob = self.hpcClass(self,conditioned_toolargv)
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/job/local.py", line 14, in __init__
    (junk, self.shell_script_template, self.runtime_config_template) = self.get_templates(None, "local_shell", "basic_local_runtime_environment")
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/job/hpc.py", line 97, in get_templates
    raise tutils.tardisException("error neither  job_template_name nor job_template_filename are defined (and no default available")
tardis.tutils.tutils.tardisException: error neither  job_template_name nor job_template_filename are defined (and no default available

**Comment by afmcc** [comment]
unfortunately testing of that fix did not pick up another issue 

crash$ tardis --hpctype local echo "hello"
reading config from /etc/tardis/tardis.toml
tool args = ['echo', 'hello']
tardis.py : logging this session to /home/mccullocha/tardis_Gpg9zo
Traceback (most recent call last):
  File "/stash/miniconda3/envs/universal2/bin/tardis", line 11, in <module>
    sys.exit(tardis_main())
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/run.py", line 244, in tardis_main
    (exit_code, factory) = run(command_args, options, checkCommandIsValid = False)
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/run.py", line 116, in run
    unsentJob.sendAvailableOutput(dc.outputCollector, dc.productCollector)
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/job/local.py", line 281, in sendAvailableOutput
    time.sleep(self.POLL_INTERVAL)
NameError: global name 'time' is not defined
crash$

**Comment by afmcc** [comment]
commit c63a42fed621af4a1ede636454db58ea21243898
Author: afmcc <alanfmcculloch@gmail.com>
Date:   Wed Jun 20 15:40:40 2018 +1200

    another patch for issue 20. Tested and resolves bug

diff --git a/tardis/job/local.py b/tardis/job/local.py
index c183975..29fd772 100755
--- a/tardis/job/local.py
+++ b/tardis/job/local.py
@@ -1,4 +1,4 @@
-import string, os, stat, subprocess, sys, re
+import string, os, stat, subprocess, sys, re, time

 import tardis.tutils.tutils as tutils
 import tardis.job.hpc as hpc

- will close when re-tested after release
