### ISSUE TITLE
if set custom job template file in toml file and use relative path, tardis later crashes 

### ISSUE THREAD

**Issue by afmcc** [AgResearch/tardis#23]

**Comment by afmcc** [comment]
error is as follows : 

Traceback (most recent call last):
  File "/stash/miniconda3/envs/universal2/bin/tardis", line 6, in <module>
    sys.exit(tardis.run.tardis_main())
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/run.py", line 244, in tardis_main
    (exit_code, factory) = run(command_args, options, checkCommandIsValid = False)
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/run.py", line 83, in run
    c.launchArrayJobs()
  File "/stash/miniconda3/envs/universal2/lib/python2.7/site-packages/tardis/conditioner/factory.py", line 147, in launchArrayJobs
    raise tutils.tardisException("hpcConditioner : %s"%stderr)
tardis.tutils.tutils.tardisException: hpcConditioner : sbatch: error: Batch script is empty!

**Comment by afmcc** [comment]
fixed : 

commit af8f5c5c2bf9b0db0d3b9928d1ea05f26ce4e12a
Author: afmcc <alanfmcculloch@gmail.com>
Date:   Fri Jun 15 11:16:56 2018 +1200

    patch for issue 23 (unable to used custom job template file)

diff --git a/tardis/tutils/tutils.py b/tardis/tutils/tutils.py
index d6764d5..ff5b747 100755
--- a/tardis/tutils/tutils.py
+++ b/tardis/tutils/tutils.py
@@ -210,9 +210,9 @@ def validateOptions(options):
     validateInt(options, "seqlength_min")
     validateInt(options, "seqlength_max")
     validateBool(options, "dry_run", required=True)
-    validatePath(options, "jobtemplatefile", checkIsFile=True)
-    validatePath(options, "shelltemplatefile", checkIsFile=True)
-    validatePath(options, "runtimeconfigsourcefile", checkIsFile=True)
+    validatePath(options, "jobtemplatefile", checkIsFile=True, makeAbsolute=True)
+    validatePath(options, "shelltemplatefile", checkIsFile=True, makeAbsolute=True)
+    validatePath(options, "runtimeconfigsourcefile", checkIsFile=True, makeAbsolute=True)
     validateBool(options, "keep_conditioned_data", required=True)
     validateBool(options, "quiet", required=True)
     validateInt(options, "max_processes", required=True)
@@ -221,7 +221,7 @@ def validateOptions(options):
     validateString(options, "hpctype", required=True)
     validatePath(options, "batonfile", checkParentIsDir=True)
     validateStringList(options, "valid_command_patterns", required=True)
-    validatePath(options, "templatedir", required=True, checkIsDir=True)
+    validatePath(options, "templatedir", required=True, checkIsDir=True)   # this option does not appear to be used currently, consider removing
     validateString(options, "shell_template_name")
     validateString(options, "job_template_name")
     validateString(options, "runtime_config_name")
